// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:splitlocal/features/expenses/models/expense_category.dart';
import 'package:splitlocal/features/expenses/models/split_mode.dart';
import 'package:splitlocal/features/expenses/models/transaction.dart';
import 'package:splitlocal/features/expenses/models/transaction_type.dart';
import 'package:splitlocal/features/groups/models/group.dart';
import 'package:splitlocal/features/groups/models/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(GroupAdapter());
    registerAdapter(SplitModeAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(GroupAdapter());
    registerAdapter(SplitModeAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserAdapter());
  }
}
